spring.application.name: payments
server.port: 8081
spring.kafka:
  bootstrap-servers: 127.0.0.1:36995
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

spring.output.ansi.enabled: ALWAYS
spring:
  h2:
    console:
      enabled: true
logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.apache.kafka.clients:
      consumer.ConsumerConfig: ERROR
      producer.ProducerConfig: ERROR